repos:
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.29.0
    hooks:
      - id: check-github-workflows
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        types_or: [yaml, markdown, html, css, scss, javascript, json]
